# Generated by Django 3.2.12 on 2022-03-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employers_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='children', to='main.Employers'),
        ),
    ]
